version: '3.1'
name: xx-monitor-bot

x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "10"
      compress: "true"

services:

  mongo:
    image: mongo:6.0.6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME          # Value-less variables are pulled directly from .env
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./mongo/db:/data/db
    command: --quiet
    <<: *default-logging

  bot:
    restart: always
    depends_on: 
      - mongo
    build:
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    <<: *default-logging
