version: '3.1'
name: xx-monitor-bot
services:

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME          # Value-less variables are pulled directly from .env
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/config:/data/configdb
    ports:
      - ${MONGO_PORT}:27017
    command: --quiet    

  bot:
    restart: always
    depends_on: 
      - mongo
    build:
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - .env

  watchtower:
    # Watchtower will pull down your new image, gracefully shut down your existing container 
    # and restart it with the same options that were used when it was deployed initially
    # https://github.com/containrrr/watchtower
    image: containrrr/watchtower
    restart: always
    depends_on: 
      - bot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE
      - TZ
      