version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME          # Value-less variables are pulled directly from .env
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    command: --port ${MONGO_PORT} --bind_ip 0.0.0.0 --quiet

  mongo-express:
    image: mongo-express
    restart: always
    depends_on: 
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGO_URI}
